name: Spring Boot & Gradle CI Jobs (With. dev branches pull_request)

on:
  pull_request:
    branches: [ dev ]
    paths:
      - 'src/**'

jobs:
  build:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # application.yml 파일 설정
    - name: resources 폴더 생성
      run: |
        mkdir -p ./Urdego_Content_Service/src/main/resources

    - name: yml 파일 생성
      run: |
        echo "${{ secrets.CONTENT_APPLICATION_DEFAULT }}" > ./Urdego_Content_Service/src/main/resources/application.yml
        echo "${{ secrets.CONTENT_APPLICATION_DB }}" > ./Urdego_Content_Service/src/main/resources/database-prod.yml

    # gradlew를 실행시키기 위한 권한 부여
    - name: Gradlew 실행권한 부여
      run: chmod +x ./Urdego_Content_Service/gradlew

    # 빌드
    - name: 빌드
      run: |
        cd ./Urdego_Content_Service
        ./gradlew clean build -x test

  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Gradle 테스트
      run: |
        cd ./Urdego_Content_Service
        ./gradlew test




        
